// Code generated by MockGen. DO NOT EDIT.
// Source: customer.go
//
// Generated by this command:
//
//	mockgen -source=customer.go -destination=mock/customer.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	dto "github.com/8soat-grupo35/fastfood-order/internal/adapters/dto"
	entities "github.com/8soat-grupo35/fastfood-order/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerUseCase is a mock of CustomerUseCase interface.
type MockCustomerUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerUseCaseMockRecorder
	isgomock struct{}
}

// MockCustomerUseCaseMockRecorder is the mock recorder for MockCustomerUseCase.
type MockCustomerUseCaseMockRecorder struct {
	mock *MockCustomerUseCase
}

// NewMockCustomerUseCase creates a new mock instance.
func NewMockCustomerUseCase(ctrl *gomock.Controller) *MockCustomerUseCase {
	mock := &MockCustomerUseCase{ctrl: ctrl}
	mock.recorder = &MockCustomerUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerUseCase) EXPECT() *MockCustomerUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerUseCase) Create(arg0 dto.CustomerDto) (*entities.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*entities.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerUseCaseMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerUseCase)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockCustomerUseCase) Delete(customerId uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", customerId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerUseCaseMockRecorder) Delete(customerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerUseCase)(nil).Delete), customerId)
}

// GetAll mocks base method.
func (m *MockCustomerUseCase) GetAll() ([]entities.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entities.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCustomerUseCaseMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCustomerUseCase)(nil).GetAll))
}

// GetByCpf mocks base method.
func (m *MockCustomerUseCase) GetByCpf(cpf string) (*entities.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCpf", cpf)
	ret0, _ := ret[0].(*entities.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCpf indicates an expected call of GetByCpf.
func (mr *MockCustomerUseCaseMockRecorder) GetByCpf(cpf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCpf", reflect.TypeOf((*MockCustomerUseCase)(nil).GetByCpf), cpf)
}

// Update mocks base method.
func (m *MockCustomerUseCase) Update(customerId uint32, customer dto.CustomerDto) (*entities.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", customerId, customer)
	ret0, _ := ret[0].(*entities.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCustomerUseCaseMockRecorder) Update(customerId, customer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerUseCase)(nil).Update), customerId, customer)
}
