apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-order
  labels:
    app: fastfood-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-order
  template:
    metadata:
      name: fastfood-order
      labels:
        app: fastfood-order
    spec:
      containers:
        - name: fastfood-order
          image: fastfood-order
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      restartPolicy: Always