apiVersion: v1
kind: Service
metadata:
  name: fastfood-order-app
spec:
  selector:
    app: fastfood-order-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  