apiVersion: v1
kind: Service
metadata:
  name: fastfood-order
spec:
  selector:
    app: fastfood-order
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 32100
      targetPort: 8000
  type: NodePort
  